| Retinal features (SD)<sup>†</sup>                                                                                                                                                                                                                                                                        |                    |                    |         |
| -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------ | ------------------ | ------- |
|    Optic disc diameter (vertical, μm)                                                                                                                                                                                                                                                                    | 149.73 (15.11)     | 140.36 (13.69)     | <0.0001 |
|    Optic disc diameter (horizontal, μm)                                                                                                                                                                                                                                                                  | 136.81 (14.98)     | 127.07 (12.49)     | <0.0001 |
|    Optic cup diameter (vertical, μm)                                                                                                                                                                                                                                                                     | 67.88 (16.02)      | 69.76 (16.39)      | 0.013   |
|    Optic cup diameter (horizontal, μm)                                                                                                                                                                                                                                                                   | 66.76 (17.15)      | 67.48 (14.55)      | 0.34    |
|    Cup-disc ratio (vertical)                                                                                                                                                                                                                                                                             | 0.449 (0.078)      | 0.494 (0.089)      | <0.0001 |
|    Cup-disc ratio (horizontal)                                                                                                                                                                                                                                                                           | 0.482 (0.086)      | 0.528 (0.082)      | <0.0001 |
|    Vessel density                                                                                                                                                                                                                                                                                        | 0.031 (0.005)      | 0.026 (0.005)      | <0.0001 |
|    Tortuosity density                                                                                                                                                                                                                                                                                    | 0.676 (0.045)      | 0.672 (0.047)      | 0.075   |
|    Artery fractal dimension                                                                                                                                                                                                                                                                              | 1.134 (0.051)      | 1.157 (0.056)      | <0.0001 |
|    Vein fractal dimension                                                                                                                                                                                                                                                                                | 1.162 (0.049)      | 1.184 (0.053)      | <0.0001 |
|    Central retinal arteriolar equivalent<sup>‡</sup>                                                                                                                                                                                                                                                     | 17369.69 (1798.84) | 17251.10 (1942.61) | 0.178   |
|    Central retinal venular equivalent<sup>‡</sup>                                                                                                                                                                                                                                                        | 20684.20 (1804.86) | 20425.50 (1821.25) | 0.002   |
|    Arteriolar-venular ratio<sup>‡</sup>                                                                                                                                                                                                                                                                  | 0.842 (0.086)      | 0.847 (0.082)      | 0.237   |



† Not all images were included for estimation according to the pipeline of the AutoMorph (details in appendix p).

‡ Hubbard method was employed for estimation.                                                                                                                                                                                                                                                         


Abbreviations: 
- SD=standard deviation
